### ISSUE TITLE
Deprecate the "Master" nomenclature

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/OpenSearch-Dashboards#1318]
# Background
Coming from https://github.com/opensearch-project/OpenSearch/issues/2589.

[OpenSearch](https://github.com/opensearch-project/OpenSearch) repository is going to replace the terminology "master" with "cluster manager".
issue: https://github.com/opensearch-project/OpenSearch/issues/472#issuecomment-960298995, with the plan for its terminology replacement.

Although the existing usages with "master" will be supported in OpenSearch version 2.x to keep the backwards compatibility, please prepare for the nomenclature change in advance, and replace all the usages with "master" terminology in the code base.
All the OpenSearch REST APIs and settings that contain "master" terminology will be deprecated in 2.0, and alternative usages will be added.

# Solution
Replace the terminology "master" with "cluster manager".

When being compatible with OpenSearch 2.0:
- Replace "master" in code comment and internal variable / function name
- Replace OpenSearch REST API that contains "master" with the provided inclusive REST API
- Replace "master" in documentation

## Tasks

- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1685
  - In progress owned by @manasvinibs 
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1686
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1687
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1688
  - In review owned by @manasvinibs 
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1689
  - In review owned by @manasvinibs 
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1690
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1691
  - Assigned to @kaddy645 
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1692
  - In progress owned by @manasvinibs

**Comment by dblock** [comment]
@tlfeng Can you please create sub-issues for all OpenSearch Dashboards plugins and link them from here?

**Comment by tlfeng** [comment]
About Dashboards plugin, I looked through and did a search for "master" keyword in all the repositories of Dashboards plugins.
Only Anomaly Detection Dashboards plugin has got a usage in the CI workflow for setting up a testing Docker image: https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/blob/1.3.1.0/.github/configurations/docker-compose.yml#L10

**Comment by dblock** [comment]
For 2.0, at a minimum please ensure that the plugin is not calling any deprecated APIs in core or another plugin, and confirm below, then remove the 2.0.0 label. If you have time, do the complete deprecation as described in this issue.

**Comment by tmarkley** [comment]
Dashboards is calling some of the now-deprecated APIs, but we cannot make all of those changes and have them tested by 2.0 unless we push out the release date. There is a significant amount of work required in Dashboards and the JS client.

**Comment by tmarkley** [comment]
Expectations are:

1. If plugins/Dashboards are using deprecated APIs from the engine, we should remove them in 2.0.
2. If plugins/Dashboards are providing APIs with non-inclusive word, we should deprecate them in 2.0 too.
3. If plugins/Dashboards are using non-inclusive words internally (code, comment, etc), it is okay to make the change by 2.1.  But 2.0 is still preferred.

**Comment by tmarkley** [comment]
## Instances of `master` [work in progress]

### OpenSearch APIs


### OpenSearch Dashboards APIs


### Other Code

#### `isDevClusterMaster` config

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-config/src/env.test.ts#L61

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-config/src/env.ts#L39-L140

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-config/src/__mocks__/env.ts#L55-L56

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-config/src/__snapshots__/env.test.ts.snap#L24-L235

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/core/server/bootstrap.ts#L85

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/core/server/http/http_service.test.ts#L278

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/core/server/http/http_service.ts#L172

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/core/server/legacy/legacy_service.test.ts#L376-L405

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/core/server/legacy/legacy_service.ts#L158

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/core/server/plugins/plugins_service.ts#L140

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/src/core/test_helpers/osd_server.ts#L93


#### Incorrect references to `master` branch 

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/examples/bfetch_explorer/public/plugin.tsx#L78

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/examples/developer_examples/README.md?plain=1#L17

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/examples/embeddable_explorer/public/plugin.tsx#L89

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/examples/routing_example/public/app.tsx#L70-L93

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/examples/routing_example/public/plugin.tsx#L64-L79

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/examples/search_examples/README.md#L9

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/examples/state_containers_examples/public/plugin.ts#L83-L137

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/examples/ui_actions_explorer/public/plugin.tsx#L137

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/examples/url_generators_explorer/public/plugin.tsx#L73

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/opensearch-eslint-config-opensearch-dashboards/typescript.js#L100

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-config/src/config_service.test.ts#L45

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1caf90752d8e34ceece81d8a69f6ec79aabfa9c1/packages/osd-config/src/env.test.ts#L39

**Comment by ananzh** [comment]
nodejs client "Master" deprecation is summarized [here](https://github.com/opensearch-project/opensearch-js/issues/221)

**Comment by kavilla** [comment]
Master has been deprecated. Closing this issue. New issue to track the removal of these deprecated terms.
