### ISSUE TITLE
Deprecate the "Blacklist / Whitelist" nomenclature

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/OpenSearch-Dashboards#1319]
# Background
[OpenSearch](https://github.com/opensearch-project/OpenSearch) repository is going to replace the terminology "blacklist / whitelist" with "denylist / allowlist".
issue: https://github.com/opensearch-project/OpenSearch/issues/1483, with the plan for its terminology replacement.

Although the existing usages with "master" will be supported in OpenSearch version 2.x to keep the backwards compatibility, please prepare for the nomenclature change in advance, and replace all the usages with "master" terminology in the code base.
All the OpenSearch REST APIs and settings that contain "master" terminology will be deprecated in 2.0, and alternative usages will be added.

# Solution
Replace the terminology "blacklist" with "denylist".
Replace the terminology "whitelist" with "allowlist".

When being compatible with OpenSearch 2.0:
- Replace "blacklist" in descriptive text
- Replace "whitelist" in descriptive text and internal variable name
- Replace "whitelist" in setting name
- Replace "whitelist" in documentation

## Tasks

- [x] Deprecate `http.compression.referrerWhitelist` in favor of `http.compression.referrerAllowlist` (   Unknown configuration key(s)/ does not exists)
- [x] Deprecate `http.compression.referrerWhitelistConfigured` in favor of `http.compression.referrerAllowlistConfigured`(   Unknown configuration key(s)/ does not exists)
- [x] Deprecate `http.xsrf.whitelist` in favor of `http.xsrf.allowlist` (   Unknown configuration key(s)/ does not exists)
- [x] Deprecate `http.xsrf.whitelistConfigured` in favor of `http.xsrf.allowlistConfigured`
- [x] Deprecate `opensearch.requestHeadersWhitelist` in favor of `opensearch.requestHeadersAllowlist`
- [x] Deprecate `opensearch.requestHeadersWhitelistConfigured` in favor of `opensearch.requestHeadersAllowlistConfigured`
- [x] Deprecate `server.compression.referrerWhitelist` in favor of `server.compression.referrerAllowlist`
- [x] Deprecate `server.xsrf.whitelist` in favor of `server.xsrf.allowlist`
- [x] Replace `blacklist` with `denylist` in comments and local variables
- [x] Replace `whitelist` with `allowlist` in comments and local variables

# Non-inclusive instances of `blacklist` and `whitelist`

## APIs, configuration

<details><summary><code>http.compression.referrerWhitelist</code> config</summary>
<p>

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/http/http_config.test.ts#L235-L268

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/http/http_config.ts#L80

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/http/http_config.ts#L120-L121

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/http/http_server.test.ts#L857-L862

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/http/http_server.ts#L285

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/http/__snapshots__/http_config.test.ts.snap#L103-L116

</p>
</details>

<details><summary><code>http.compression.referrerWhitelistConfigured</code> config</summary>
<p>

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/core_usage_data/core_usage_data_service.mock.ts#L68

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/core_usage_data/core_usage_data_service.test.ts#L120

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/core_usage_data/core_usage_data_service.ts#L201

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/core_usage_data/types.ts#L110

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/plugins/opensearch_dashboards_usage_collection/server/collectors/core/core_usage_collector.ts#L75

</p>
</details>

<details><summary><code>http.xsrf.whitelist</code> config</summary>
<p>

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/core_usage_data/core_usage_data_service.ts#L205

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/http/cookie_session_storage.test.ts#L75

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/http/http_config.test.ts#L179-L187

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/http/http_config.ts#L96

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/http/http_config.ts#L156

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/http/lifecycle_handlers.test.ts#L76-L170

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/http/lifecycle_handlers.ts#L43-L48

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/http/test_utils.ts#L57

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/http/__snapshots__/http_config.test.ts.snap#L86

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/http/integration_tests/lifecycle_handlers.test.ts#L50-L249

</p>
</details>

<details><summary><code>http.xsrf.whitelistConfigured</code> config</summary>
<p>

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/server.api.md#L419

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/core_usage_data/core_usage_data_service.mock.ts#L113

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/core_usage_data/core_usage_data_service.test.ts#L171

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/core_usage_data/core_usage_data_service.ts#L205

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/core_usage_data/core_usage_data_service.ts#L205

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/core_usage_data/types.ts#L114

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/plugins/opensearch_dashboards_usage_collection/server/collectors/core/core_usage_collector.ts#L79

</p>
</details>

<details><summary><code>opensearch.requestHeadersWhitelist</code> config</summary>
<p>

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/config/opensearch_dashboards.yml#L90-L93

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/packages/osd-apm-config-loader/__fixtures__/en_var_ref_config.yml#L5

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/packages/osd-apm-config-loader/src/utils/__snapshots__/read_config.test.ts.snap#L100

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/packages/osd-config/__fixtures__/en_var_ref_config.yml#L5

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/packages/osd-config/src/raw/__snapshots__/read_config.test.ts.snap#L100

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/server.api.md#L353

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/server.api.md#L415

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/server.api.md#L1231

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/server.api.md#L1424

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/server.api.md#L1443

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/core_usage_data/core_usage_data_service.ts#L176

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/opensearch/opensearch_config.test.ts#L88-L444

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/opensearch/opensearch_config.ts#L77-L317

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/opensearch/opensearch_service.test.ts#L153-L344

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/opensearch/client/client_config.test.ts#L42

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/opensearch/client/client_config.ts#L50

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/opensearch/client/cluster_client.test.ts#L46-L391

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/opensearch/client/cluster_client.ts#L118-L121

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/opensearch/legacy/cluster_client.test.ts#L262-L578

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/opensearch/legacy/cluster_client.ts#L229

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/opensearch/legacy/opensearch_client_config.test.ts#L51-L662

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/opensearch/legacy/opensearch_client_config.ts#L55

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/plugins/console/server/types.ts#L47

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/plugins/console/server/routes/api/console/proxy/create_handler.ts#L86

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/plugins/console/server/routes/api/console/proxy/tests/mocks.ts#L45

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/plugins/console/server/routes/api/console/proxy/tests/proxy_fallback.test.ts#L56

</p>
</details>

<details><summary><code>opensearch.requestHeadersWhitelistConfigured</code> config</summary>
<p>

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/server.api.md#L448

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/core_usage_data/core_usage_data_service.mock.ts#L48

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/core_usage_data/core_usage_data_service.test.ts#L185

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/core_usage_data/core_usage_data_service.ts#L175

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/core_usage_data/types.ts#L83

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/plugins/opensearch_dashboards_usage_collection/server/collectors/core/core_usage_collector.ts#L48

</p>
</details>

<details><summary><code>server.compression.referrerWhitelist</code> config</summary>
<p>

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/config/deprecation/core_deprecations.ts#L160

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/test/api_integration/config.js#L51

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/test/api_integration/apis/core/index.js#L47-L57

</p>
</details>

<details><summary><code>server.xsrf.whitelist</code> config</summary>
<p>

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/packages/osd-config/src/legacy/legacy_object_to_config_adapter.test.ts#L108-L134

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/packages/osd-config/src/legacy/__snapshots__/legacy_object_to_config_adapter.test.ts.snap#L29-L60

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/config/deprecation/core_deprecations.test.ts#L95-L102

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/config/deprecation/core_deprecations.ts#L53-L158

</p>
</details>

## Other code

<details><summary>Comments/variables</summary>
<p>

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/saved_objects/mappings/lib/get_root_properties_objects.test.ts#L182

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/plugins/home/server/tutorials/santa_logs/index.ts#L55

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/packages/opensearch-safer-lodash-set/scripts/update.sh#L25

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/core/server/http/http_server.test.ts#L872-L881

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/dev/license_checker/config.ts#L33

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/dev/license_checker/config.ts#L89

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/dev/license_checker/index.ts#L31

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/dev/license_checker/run_check_licenses_cli.ts#L35-L59

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/plugins/home/public/application/components/tutorial/content.js#L35-L43

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/plugins/home/public/application/components/tutorial/__snapshots__/content.test.js.snap#L8

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/plugins/home/server/tutorials/santa_logs/index.ts#L55

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/plugins/opensearch_dashboards_react/public/markdown/markdown.test.tsx#L89-L110

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/plugins/opensearch_dashboards_react/public/markdown/markdown.tsx#L40-L110

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/plugins/opensearch_dashboards_react/public/markdown/__snapshots__/markdown.test.tsx.snap#L27

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/plugins/vis_type_timeseries/common/ui_restrictions.ts#L42-L52

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/plugins/vis_type_timeseries/server/lib/search_strategies/default_search_capabilities.js#L52-L68

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/376ba8cf51711a8b6b61f1b6c344e6cee21763ec/src/plugins/vis_type_timeseries/server/lib/search_strategies/default_search_capabilities.test.js#L53-L55

</p>
</details>

**Comment by boktorbb-amzn** [comment]
Resolved in #1467

**Comment by tmarkley** [comment]
There are still instances of `blacklist`/`whitelist` in code that needs to be addressed. I will edit this comment with the list.
