### ISSUE TITLE
[D&D] Make new "meta" state slice to keep track of things we don't want to save and load

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#1879]
After #1870, we need to further [expand and refine the behavior of `hasUnappliedChanges`](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/8c50d0f87d4036e5bdb7bb18a09a3f52f214e6b3/src/plugins/wizard/public/application/components/top_nav.tsx#L29-L31).

We should keep track of whether the canvas is in a savable state or not, and only enable the save button when the current state is valid _and_ the canvas is rendering the current state. The best way of doing so may be creating a new "meta" state slice, which we can use to keep track of this (and other properties) that we don't want to include in save and load payloads.

- [ ] Save button should be disabled with an empty canvas, or any time there's not yet enough required information to render a vis
- [x] Save button should be disabled when agg editing suspends realtime updates
- [ ] Save button should be disabled when there have been no changes to a loaded vis
- [ ] [Tooltip](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/8c50d0f87d4036e5bdb7bb18a09a3f52f214e6b3/src/plugins/wizard/public/application/utils/get_top_nav_config.tsx#L75-L81) and/or toast should provide info on why the vis is not saveable and how to fix
- [ ] Savable state should not be part of `Visualization` or `Style` slices, because it should not be saved/loaded.

**Comment by joshuarrrr** [comment]
New metadata slice was created in #1953, #1965.
