### ISSUE TITLE
[MD] Meta issue from feedback session & comments in closed PR

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/OpenSearch-Dashboards#2433]
Issues created based on #2400,  https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2409, https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2399

- [x] #2210
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2434
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2435
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2427
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2426
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2431
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2489

**Comment by mpabba3003** [comment]
[ ]  Documentation for "data_source" plugin
[ ]  Documentation for "data_source_management" plugin

**Comment by zhongnansu** [comment]
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2409#discussion_r981731054 
@mpabba3003 please take a look

**Comment by zhongnansu** [comment]
need to create issue for this comment https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2400#issuecomment-1254337310

**Comment by seraphjiang** [comment]
GLOBAL APP TO DO:
https://github.com/opensearch-project/ux/issues/16

- [ ] If an error is present on any page within the application due to a provided endpoint becoming unavailable or authentication failing, present user with a toast message appropriate to the error case -- defer to 2.5
 
 kroosh to update issue with approved error messages following writing meeting -- need more clarification to understand, defer to 2.5 or next 


## STACK MANAGEMENT NAVIGATION TO DO:

 https://github.com/opensearch-project/ux/issues/17 -- done, need to raise a pr. 

##  DATA SOURCE LIST COMPONENT:

 https://github.com/opensearch-project/ux/issues/18
 https://github.com/opensearch-project/ux/issues/19
 https://github.com/opensearch-project/ux/issues/21
 https://github.com/opensearch-project/ux/issues/22


## CREATE DATA SOURCE CONNECTION:

 https://github.com/opensearch-project/ux/issues/23
 https://github.com/opensearch-project/ux/issues/24
 https://github.com/opensearch-project/ux/issues/25
 https://github.com/opensearch-project/ux/issues/26
 https://github.com/opensearch-project/ux/issues/27  -- defer to 2.5
 https://github.com/opensearch-project/ux/issues/28 -- frontend validation 


## UPDATE DATA SOURCE COMPONENT:

a lot validation enhancement.

 https://github.com/opensearch-project/ux/issues/29
 Update authentication section -- need to change drop down and description
 Change authentication details to authentication method 
 update ui to reflect radio button selection
 update Description input box label to Description - optional
 Implement error handling on all required input boxes
 Check for required value onBlur and onChange. If required value is missing, input box state changes to Error and user is prevented from submitting form (submit button disabled state)
 update Update Password modal to include rendered username
 Remove old password from Update Password modal
 update delete modal text
 update Update Password button to read Update Stored Password
 Update Update Password modal header to Update stored password


## INDEX PATTERN COMPONENT:

 Implement experimental feature warning call out (OUICallout)
 Update table to include data source column - always float default to top, mark default with badge (OUIBadge) -- need more discussion, too later to add to 2.4

INDEX PATTERN CREATE  WIZARD 
STEP 1:

 Implement warning call out (OUICallout)
STEP 2 :

 Implement warning call out (OUI Callout)

 Update index pattern name input box to display Data Source before input box - data source is not editable
STEP 3 :

 Implement warning call out (OUI Callout)
