### ISSUE TITLE
[MD] Meta issue from bug bash

### ISSUE THREAD

**Issue by kristenTian** [opensearch-project/OpenSearch-Dashboards#2592]
Data source

- [x] [Provide valid OpenSearch Dashboards' document link ](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2593)
- [ ] [Create Data source with roles of no relevant permission - should render proper error state](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2594)
- [x]  [After save the data source updates, should stay on current page](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2595)
 
Index Pattern
- [x] #2591 
- [ ] #2597
- [x] #2598

Discover
- [ ] #2599

**Comment by kristenTian** [comment]
closing for scope of 2.4 are done.
