### ISSUE TITLE
[Vis Builder] Data persistence Meta Issue

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#2762]
Data persistence meta issue for vis-builder. 

Research and documentation tasks:

- [x] Research and document on the various persistence solution's (both existing solutions in OSD and external) https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2876
- [x] Research and document on how current plugin can persist their global data on the nav bar. https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2901
- [x] Research and document the proposal on how we can persist aggregation data when switching vis type in Vis Builder. https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2900

Implementation tasks:
- [x] Persist the global query parameters including global filters, time range and time refresh intervals; the data should persist after a page refresh or navigate to other data persistent app such as visualize, discover, timeline and dashboards.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1913
- [x] Persist redux data #2898
- [x] Persist app query and app filter for vis builder #3089 
- [x] Persist agg data when switching among vis type area, line and histogram https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3157
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2763

Other persistence related issues: 
- [x] Internal states persistence https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3124
- [ ] Redo and undo #3102
- [ ] Filter does not persist when adding to dashboard https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3146
