### ISSUE TITLE
[Epic] [Visualizations] Consolidate visualization-rendering to Vega-Lite

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#2819]
This is the meta-issue/epic to track all the migration and deprecation tasks as we consolidate visualization rendering as described in #2385.

### Update Vega-Lite to latest version

Upgrade `vega-lite` from current (`^4.16.8`) to latest (`5.4.0`)
 - [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2717

### Implement common interaction patterns in Vega-Lite

- [ ] Audit Vega-Lite tooltip implementation against other visualization types
- [ ] Audit Vega-Lite selection/filter interactions (click, brush) against other visualization types
- [ ] Audit Vega-Lite legend styling, layout, and interactions against other visualization types

### Migrate VisBuilder visualization types to Vega-Lite

We'll use the simplified vis type integrations within VisBuilder to refine the vislib -> vega-lite migration approach.

- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1619
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2378
- [x] #3253
- [x] #3254
- [x] #3255
- [ ] #3270

### Migrate Elastic Chart-rendered components to Vega-Lite

- [ ] Migrate TSVB plugin to Vega-Lite rendering
- [x] #4643
- [ ] Migrate Alerting plugin charts to built-in chart types
- [ ] Migrate Anomaly Detection plugin charts to built-in chart types

### Migrate and refactor `timeline` visualizations

- [ ] #3389
- [x] #3388

### Migrate VisLib charts to Vega-Lite

(Or deprecate in favor of VisBuilder implementations)

- [ ] Support incremental rollout of vega-lite rendering based on capabilities implemented
- [ ] #2820
- [x] #3256
- [x] #3257
- [x] #3258
- [ ] Migrate heatmap vis type to Vega-Lite rendering
- [x] #3259
- [ ] Migrate gauge vis type to Vega-Lite rendering
- [ ] Migrate goal vis type to Vega-Lite rendering

**Comment by Bigpet** [comment]
Is this still up-to-date? I see this comment implying migration to EChart is under-way?

https://github.com/opensearch-project/OpenSearch-Dashboards/pull/11077#discussion_r2645322649
