### ISSUE TITLE
[Epic] [Feature] "Point in time" search OpenSearch Dashboards integration 

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#2909]
This is the epic issue for tracking all Point In Time tasks within OpenSearch Dashboards

OpenSearch Meta Issue: https://github.com/opensearch-project/OpenSearch/issues/3959
User request: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1268
UX mocks and discussion: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1612

- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2127
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1998
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1999
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2000

All related issues should be labeled with https://github.com/opensearch-project/OpenSearch-Dashboards/labels/feature-PIT
