### ISSUE TITLE
[Feature Anywhere] [Meta] Add documentation for Feature Anywhere

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/OpenSearch-Dashboards#3383]
Coming from #2880

We will want to have clear documentation in READMEs to show the following:

- [x] purpose of the `vis_augmenter` plugin and how it works
- [x] examples of each added data model (a `VisLayer`, a `PluginResource`, an `augment-vis` saved object, a `vis_layer` expressions function)
- [x] detailed steps on how to onboard a plugin. This should live in the `vis_augmenter` README, as well as a standalone blog. It may reference plugin documentation with examples
- [x] examples, usage, & purpose of the new `vis_augmenter/stats` API
- [x] limitations / gotchas of the feature (e.g., default limit of 10 resources per vis)
- [x] the loose coupling, such as freedom to make visualizations ineligible, add plugin resources that are unrelated to the vis, etc.
