### ISSUE TITLE
[Multiple Datasource][Meta] Feature GA in 2.7 release

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/OpenSearch-Dashboards#3577]
Multiple Datasource was first released in 2.4 as an experimental feature. This is the meta issue to track all the items we'll deliver to bring Multiple Datasource out of experimental, targeting 2.7 release.

- Feature: Integrate Multiple Datasource with dev tool console
  - [x] prerequisite: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3546
  - [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2699 
  - [x] must have bug fix: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3645
  - [x] good to have bug fix: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3515
- Feature: Enable users to create index patterns for indices with same name but from different datasources
  - [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2597
  - [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2599
- UI/UX refactor
  - [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3551 
  - [x] #3579
  - [x] #3806

**Comment by zhongnansu** [comment]
All PRs are opened

**Comment by joshuarrrr** [comment]
All tasks completed
