### ISSUE TITLE
[Multiple Datasource] Support serverless AWS OpenSearch in SigV4 auth type

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/OpenSearch-Dashboards#3623]
## Problem statement

Multiple datasource should be able to connect to serverless AWS OpenSearch: https://aws.amazon.com/opensearch-service/features/serverless/ 

### UI/UX changes (proposal only)
To create a serverless data source, there needs to be a way for user to specify serverless opensearch. I propose a new required field `service type` in the "create data source" flow, with options `AWS OpenSearch` and `AWS OpenSearch serverless`. Below image only explains the proposal. Please help with actual UI mock-up @shanilpa, and the correct naming. 
![image](https://user-images.githubusercontent.com/32652829/233209138-a9e07196-805f-41e6-88b2-aef0f3587d28.png)

## Task breakdown
- [x] POC & Research
- [x] refactor `test_connection` to remove the use of `.info()` API, because  `.info()` API is not supported in serverless. Use `ping()` instead
- [x] refactor schema for datasource of sigV4 type,  to add field of `service`, candidates values are `es` or `aoss`
- [x] refactor UI to let user to specify serverless or regular aws opensearch, when creating data source with sigV4 auth type.
- [x] support both legacy datasource client and new datasource client 
- [x] update functional tests: https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/665

## Reference:
- Opensearch-js client 2.x  has support for serverless Opensearch: https://github.com/opensearch-project/opensearch-js/issues/356

- Similar issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3718

**Comment by zhongnansu** [comment]
To support serverless for legacy datasource client is not as straight-forward as new client, because legacy clients library `elasticsearch.js` doesn't 1) provide option to sign requests using sigv4.  2) provide option to set `service: aoss`.

For 1), we solved it in MD while releasing the sigV4 support in 2.6, using a third party Connection handler for Amazon ES, https://github.com/TheDeveloper/http-aws-es.  `HttpAmazonESConnector`
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/9d270234378dc06c51939b8d115beb6082c46e3b/src/plugins/data_source/server/legacy/configure_legacy_client.ts#L10
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/9d270234378dc06c51939b8d115beb6082c46e3b/src/plugins/data_source/server/legacy/configure_legacy_client.ts#L197-L208

**Comment by kavilla** [comment]
Closing per @zhongnansu
