### ISSUE TITLE
2.7.0 Platform Upgrades for Plugins (tracker)

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#3674]
For all [issues labeled 2.7.0](https://github.com/opensearch-project/OpenSearch-Dashboards/issues?q=is%3Aopen+is%3Aissue+label%3Av2.7.0), PRs must be opened by 2023-03-31 to be considered on track.

In general, the time to first review SLA for OpenSearch Dashboards is 7 days. Each PR will be assigned to a maintainer as the primary point of contact.

### GA feature launches

1. https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3577 - 7/7 [total expected PRs](https://github.com/opensearch-project/OpenSearch-Dashboards/issues?q=is%3Aopen+is%3Aissue+label%3A%22multiple+datasource%22+label%3Av2.7.0) open

### Dashboards plugin blockers

1. Geospatial blockers - 1 PR in review (https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3676)
2. Observability blockers - 1 PR in review (https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3090)

### Features and fixes

1. Dashboard feature: 1 PR in review (https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3676)
2. Dashboard feature: Table Vis fixes and follow-ups 2/3 [total expected PRs](https://github.com/opensearch-project/OpenSearch-Dashboards/issues?q=is%3Aopen+is%3Aissue+label%3Av2.7.0+label%3AtableVis)

### Known PRs

Updated 2023-04-04 from https://github.com/opensearch-project/OpenSearch-Dashboards/pulls?q=is%3Aopen+is%3Apr+label%3Av2.7.0
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3090 - only observability blocker
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3605 - only geospatial blocker
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3604
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3652
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3397
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3663
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3640
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3643 - lower priority
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3641
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2720
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3678
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3783
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3775
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3755
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3754
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3751
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3747
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3732
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3724
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3693
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3676
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3641
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3604

### Feature launches

1. Feature Anywhere - 5 [open PRs](https://github.com/opensearch-project/OpenSearch-Dashboards/pulls?q=is%3Aopen+is%3Apr+label%3Afeature-anywhere)
2. PIT - targeting 2.8 or 2.9 - 1 [open PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pulls?q=is%3Aopen+is%3Apr+label%3Afeature-PIT)

**Comment by lezzago** [comment]
Hey we have a few PRs we need in for 2.7.
#3415 
#3169 
#3145

**Comment by zhongnansu** [comment]
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3693

**Comment by zhongnansu** [comment]
adding 1 more MD PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3754

**Comment by zhongnansu** [comment]
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3755

**Comment by zhongnansu** [comment]
Add a bux fix PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3775

**Comment by zhongnansu** [comment]
[MD]Add 1 more PR to address feedback from UX and demo
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3806

**Comment by joshuarrrr** [comment]
# 2.7 OSD Release update (2023-04-12)

## Summary

15 total open PRs to `main`, 1 open backport PR to `2.x`

Format: (Size, assigned reviewer) Description - review state: PR link

### External teams

#### Observability - new dashboards list

1. (S, Josh) Deletion bug fix - initial review complete, missing tests, DCO: <https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3796>

### Major features

#### Multiple Datasource GA

1. (S, Josh) Console UI improvements - not yet reviewed: <https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3806>

#### VisBuilder

1. (M, Josh) 2 way communication using UI actions and bug fixes - initial review complete: <https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3732>
2. (M, unassigned) Adds UIState to vis, adds index patterns to embeddable, bug fixes - not yet reviewed: <https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3751>
3. (S, Rocky) Adds toast ID to toast api - initial review complete: <https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3752>

#### Table Vis

1. (L, Josh) Move format table logic to table render and consolidate types: <https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3397>
2. (S, Anan, Josh) CCI Fix table length - approved awaiting automation completion: <https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3797>
3. (S, Anan, Mana) CCI Fix table initial size - 1 approval: <https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3816>

#### Survey Link

1. (M, unassigned) Add survey link - 1 approval, but changes requested: <https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3676>

### Nice to haves

1. (M, Rocky) Omit osd-version header - not yet reviewed: <https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3643>
2. (S, Josh) CCI IE warning - 1 approval: <https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3641>
3. (M, Josh) Clean up noDocumentation links - initial review complete: <https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3685>
4. (M, Abby) Add docker files and docs for selenium tests - initial review complete: <https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3747>
5. (S, Josh) CCI Refactor and remove .kui* classes in tests - 1 approval: <https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3766>
6. (M, Rocky) CCI Replace node with scripts/use_node in functional tests - initial review complete: <https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3783/>

**Comment by joshuarrrr** [comment]
All PRs merged.
