### ISSUE TITLE
[RENAME] Renaming from kibana -> opensearch Dashboards

### ISSUE THREAD

**Issue by mihirsoni** [opensearch-project/OpenSearch-Dashboards#37]
track progress toward renaming from kibana to the new opensearch dashboards  project 

#### Methods / Comments / Variables / Docs / Classes / Interfaces

Old | New
-- | --
elasticsearch | opensearch
es | opensearch
Es | OpenSearch
kibana | opensearchDashboards
Kibana | OpenSearchDashboards
kbn | osd
KBN | OSD
Elasticsearch | OpenSearch

#### Files

Old | New
-- | --
kbn-* | osd_*
kibana | opensearch_dashboards_*

#### Directories

Old | New
-- | --
kbn-* | osd-*
kibana | opensearch-dashboards-*

#### packages 
- [ ] .ci
- [ ] elastic-datemath
- [ ] elastic-eslint-config-kibana
- [ ] elastic-safer-lodash-set
- [x] kbn-ace https://github.com/opendistro-for-elasticsearch/website/pull/40
- [x] kbn-analytics https://github.com/opendistro-for-elasticsearch/website/pull/44
- [x] kbn-apm-config-loader https://github.com/opendistro-for-elasticsearch/website/pull/78
- [x] kbn-babel-preset https://github.com/opendistro-for-elasticsearch/website/pull/52
- [x] kbn-config https://github.com/opendistro-for-elasticsearch/website/pull/64
- [x] kbn-config-schema https://github.com/opendistro-for-elasticsearch/website/pull/71
- [x] kbn-dev-utils https://github.com/opendistro-for-elasticsearch/website/pull/74
- [x] kbn-es https://github.com/opendistro-for-elasticsearch/website/pull/79
- [x] kbn-es-archiver #42 
- [x] kbn-eslint-import-resolver-kibana #45 
- [x] kbn-eslint-plugin-eslint #46 
- [x] kbn-expect #47 
- [x] kbn-i18n #48 
- [x] kbn-interpreter #49 
- [x] kbn-logging #50 
- [x] kbn-monaco #51 
- [x] kbn-optimizer #59 
- [x] kbn-plugin-generator #62 
- [x] kbn-plugin-helpers
- [x] kbn-pm
- [x] kbn-release-notes
- [x] kbn-spec-to-console
- [x] kbn-std
- [x] kbn-storybook
- [x] kbn-telemetry-tools
- [x] kbn-test
- [x] kbn-test-subj-selector https://github.com/opendistro-for-elasticsearch/website/pull/43
- [x] kbn-ui-framework https://github.com/opendistro-for-elasticsearch/website/pull/41
- [x] kbn-ui-shared-deps
- [x] kbn-utility-types https://github.com/opendistro-for-elasticsearch/website/pull/39
- [x] kbn-utils #38 

### src/plugins
- [x] advanced_settings
- [x] apm_oss
- [x] bfetch
- [x] charts
- [x] console
- [x] dashboard
- [x] data
- [x] dev_tools
- [x] discover
- [x] embeddable
- [x] es_ui_shared
- [x] expressions
- [x] home
- [x] index_pattern_management
- [x] input_control_vis
- [x] inspector
- [x] kibana_legacy
- [x] kibana_overview
- [x] kibana_react
- [x] kibana_usage_collection
- [x] kibana_utils
- [x] legacy_export
- [x] management
- [x] maps_legacy
- [x] navigation
- [x] newsfeed
- [x] region_map
- [x] saved_objects
- [x] saved_objects_management
- [x] security_oss
- [x] share
- [x] telemetry
- [x] telemetry_collection_manager
- [x] telemetry_management_section
- [x] tile_map
- [x] timelion
- [x] ui_actions
- [x] url_forwarding https://github.com/opendistro-for-elasticsearch/website/pull/94
- [x] usage_collection
- [x] vis_default_editor
- [x] vis_type_markdown
- [x] vis_type_metric
- [x] vis_type_table
- [x] vis_type_tagcloud
- [x] vis_type_timelion
- [x] vis_type_timeseries
- [x] vis_type_vega https://github.com/opendistro-for-elasticsearch/website/pull/88
- [x] vis_type_vislib
- [x] vis_type_xy
- [x] visualizations
- [x] visualize
