### ISSUE TITLE
[META] OUI Compliance Audit Tracking

### ISSUE THREAD

**Issue by BSFishy** [opensearch-project/OpenSearch-Dashboards#4111]
This issue is to track the status of auditing each plugin and core service that has custom CSS. Ping @BSFishy if this list needs to be updated :)

## Audits so far:

- [ ] `home` plugin (described here as example)
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3962
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3963
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3965
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3966
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3967
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4109

## Audit tracking issues:

- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4076
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4077
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4078
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4079
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4080
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4081
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4082
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4083
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4084
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4085
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4086
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4087
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4088
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4089
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4090
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4091
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4092
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4093
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4094
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4095
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4096
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4097
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4098
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4099
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4100
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4101
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4102
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4103
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4104
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4105
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4106

**Comment by kavilla** [comment]
Note: OUI Compliance is important but it also might not accurately reflect the entire OpenSearch Dashboard ecosystem.

For example,
https://github.com/opensearch-project/dashboards-observability/issues/484

Plugins are able to modify global styles or update OUI variables that impact the entire ecosystem presented in OpenSearch Dashboards. Visual regressions can occur outside of Core OpenSearch Dashboards.

We should add CI checks that catches potential updates downstreams while building OpenSearch Dashboards (or in here) that enables systems to check if OUI variables/styles were modified.

**Comment by joshuarrrr** [comment]
Yeah, @kavilla, I'll be adding an additional section for audits in OpenSearch Dashboards plugins that are managed by the OpenSearch project.

**Comment by kavilla** [comment]
Are we also auditing the dark mode?

For example, https://github.com/opensearch-project/ml-commons-dashboards/issues/206

**Comment by joshuarrrr** [comment]
@kavilla Did you already open an issue to document and audit dark mode?
