### ISSUE TITLE
[META] Navigation changes for administrative features

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/OpenSearch-Dashboards#4133]
This issue is to track the status of navigation changes for administrative features. 

**The impacted plugins are:**
1. Index Management 
2. Snapshot Management
3. Notifications
4. Security
5. Stack Management(Dashboards)

- [x] https://github.com/opensearch-project/index-management-dashboards-plugin/issues/758
- [x] https://github.com/opensearch-project/dashboards-notifications/issues/48
- [x] https://github.com/opensearch-project/security-dashboards-plugin/issues/1435
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4132

### Navigations Organized Today

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/113890546/5c7ce7ee-d46c-45fa-ab57-bb5406f29472)

### New Organized Navigations 

We are proposing changes to the navigation menu in Dashboards. The most common administrative features will be moved into the existing Management section to help users easily find the features they need to manage OpenSearch. In the Management section, we are also adding an Overview page to act as a launchpad to help new Admin users discover management features and help existing users quickly access their common tasks.

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/113890546/59dc9e05-3b83-447d-aeb8-071cca249ecb)

Users clicking on one of the features will be redirected to the default page of that feature, similar to today’s interaction. For example, clicking on “Index Management’ will take users to the ”State management policies“ page:

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/113890546/082d281e-95a4-42f0-afd4-ba9afea34ba8)

### New Overview page

Under the "Management" section, users can click on the Overview page to see all of the administrative features. Each feature is shown as a widget and provides a short description and common actions for that feature.

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/113890546/c707f8ab-ee67-407e-8939-dd2c9789e698)

### Renaming Stack Management

“Stack Management” will be renamed to “Dashboards Management” to help users find configurations for Dashboards UI and managing Dashboards objects such as index patterns and visualizations.

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/113890546/97d3df1d-1533-44a4-b6a6-c10689358bbd)

### Updates to the App directory
In the “App directory” page, the original tile “Stack Management” will be repurposed. It will be named as “Management” with the description text “Your central location for managing the OpenSearch Stack.” Clicking on this tile will direct users to the Overview page of Management:

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/113890546/15b0eafd-5f3e-45de-8418-1bf69c50faec)

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/113890546/4b62dcb1-5673-47d9-9724-770f8d9851a7)

**Comment by Hailong-am** [comment]
cc @kamingleung @mnkugler @xluo-aws

**Comment by joshuarrrr** [comment]
@Hailong-am I'm excited for this re-organization. I understand how we can coordinate project-published plugins to put add their navigation links to the correct menu, but I think we'll also need to make sure we have documented guidance for external plugins about what criteria they should use to decide whether to register themselves to the Control Center section vs another menu section.

**Comment by ashwin-pc** [comment]
I'm wondering if we need to make a similar division within  the apps page too? Right now it's a list of apps with no separation.

**Comment by kamingleung** [comment]
> @Hailong-am I'm excited for this re-organization. I understand how we can coordinate project-published plugins to put add their navigation links to the correct menu, but I think we'll also need to make sure we have documented guidance for external plugins about what criteria they should use to decide whether to register themselves to the Control Center section vs another menu section.

@joshuarrrr That's a good point, I am wondering where would be a good place for this guidance? This seems to be geared towards developers. Does it make sense to be referenced somewhere on the documentation website, @vagimeli?

**Comment by nateynateynate** [comment]
I love it. Maybe we could throw in some settings where you can star the ones you want to appear at the top? A "favorites" section for the things you click on most?

**Comment by vagimeli** [comment]
> > @Hailong-am I'm excited for this re-organization. I understand how we can coordinate project-published plugins to put add their navigation links to the correct menu, but I think we'll also need to make sure we have documented guidance for external plugins about what criteria they should use to decide whether to register themselves to the Control Center section vs another menu section.
> 
> @joshuarrrr That's a good point, I am wondering where would be a good place for this guidance? This seems to be geared towards developers. Does it make sense to be referenced somewhere on the documentation website, @vagimeli?

@kamingleung @joshuarrrr I support putting the guidance on the documentation site. It seems logical that devs would go to the documentation site for this information. Do you know of any reason we should put the guidance elsewhere?

**Comment by ashwin-pc** [comment]
Whats the plan for this page under the new nav changes here? https://playground.opensearch.org/app/home#/feature_directory

**Comment by Hailong-am** [comment]
> Whats the plan for this page under the new nav changes here? https://playground.opensearch.org/app/home#/feature_directory

There has an administrative tab, we could put them into this tab also.
<img width="1255" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/113890546/036f5a39-2981-4ee6-9195-9deda22ef6a3">

**Comment by Hailong-am** [comment]
> I love it. Maybe we could throw in some settings where you can star the ones you want to appear at the top? A "favorites" section for the things you click on most?

Maybe we could reuse "Recently Viewed"

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/113890546/767d6962-5ffe-496d-b970-d48f8d74d624)
