### ISSUE TITLE
[Meta] Create styleint rules for typographic theme variables

### ISSUE THREAD

**Issue by joshuarrrr** [opensearch-project/OpenSearch-Dashboards#4302]
- [ ] Add rule to prevent plugin modification of OSD-defined classes
- [ ] Add rule to prevent plugin modification of all classes starting with `eui` or `oui`, as these are reserved namespaces for OUI
- [ ] Add rule to check all color values against allowlist from OUI generated color JSON
- [ ] Add rule to check all font family definitions
