### ISSUE TITLE
[Meta] Preview Theme `Next` 

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/OpenSearch-Dashboards#4675]
- [ ] Switch all users over to theme `Next` in the version release but honor previously chosen light or dark mode preferences 
- [ ] Present user with `OuiModal` as designed at first time user experience of the version release
- [ ] Allow user with appropriate permissions to choose Theme and screen mode (light, dark or automatic) in Advanced Settings

**Comment by KrooshalUX** [comment]
@joshuarrrr  can you follow up here with the needed playground issues? 

we should probably suppress the notification on playground since users will not be able to revert to v7

**Comment by joshuarrrr** [comment]
Yeah, I'll relabel

**Comment by joshuarrrr** [comment]
Oh, I can't move it on the project roadmap board. @DarshitChanpura can you do that?

**Comment by DarshitChanpura** [comment]
@joshuarrrr I'm not able to move it either.

**Comment by hdhalter** [comment]
@joshuarrrr or @DarshitChanpura - Can we also add it to the scorecard project? (I'm not sure who's covering for Monica.) And are there doc implications for this? Thanks.

**Comment by hdhalter** [comment]
> @joshuarrrr or @DarshitChanpura - Can we also add it to the scorecard project? (I'm not sure who's covering for Monica.) And are there doc implications for this? Thanks.

@joshuarrrr , @DarshitChanpura - Can you please add this to the scorecard project? Do you anticipate any documentation updates as a result of this change? Thanks!

**Comment by DarshitChanpura** [comment]
@hdhalter I do not have the privileges to add it there. @joshuarrrr Would you be able to move it and answer @hdhalter 's question?

**Comment by vagimeli** [comment]
Associated doc PRs for 2.12:

- https://github.com/opensearch-project/documentation-website/pull/6004
