### ISSUE TITLE
[Meta][Discover][Functional Test] Capturing Customer Feedback and Bugs into tests for Discover

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#5713]
As OpenSearch Dashboards evolves, particularly the Discover component, user feedback and bug reports have become a critical source of insights. These observations are more than just technical issues; they represent diverse user experiences and expectations. Our goal is to meticulously document these findings and integrate them into functional tests, ensuring the Discover component not only resolves current challenges but also evolves to offer an enhanced user experience. This issue will be served as a meta tracker to document the progress of transferring these understanding to tests.

- [ ] Function Test Suite 1: Line wrapping/multiple lines
* Should verify line wrapping functionality, ensure multiple lines are displayed correctly without overlapping or truncating.
    * Issue: [#5227](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5227), [#4859](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4859), [#5404](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5404)

- [ ] Function Test Suite 2: Copy data without extra data
* Should test copy functionality, ensuring only relevant data is copied without additional information.
    * Issue: [#5570](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5570)

- [ ] Function Test Suite 3: Display Multiple Documents
* Should test that multiple documents can be displayed and interacted with concurrently in the Discover interface.
    * Issue: [#5555](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5555)

- [ ] Function Test Suite 4: Data Source Selector
* Should filter index pattern
    * Issue: [#5604](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5604), [#5681](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5681)
    * Test: Test the filtering functionality listing of index patterns in the data source selector.
* Should list index patterns alphabetially in the data source selector
    * Issue: [#5609](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5609)
    * Test: Test the order of index pattern list.

- [ ] Function Test Suite 5: Left Navigation Display
* Left side navigation should be expandable and collapsable
    * Issue: [#4780](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4780), [#5671](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5671)
* _source should be in the Selected Fields section when open discover. When open discover, _source field should be automatically included in selected fields 
* Timestamp column should not be added to the selected field when remove a column. Test adding and removing various columns, including timestamp column, and verify the correct update in selected fields.
    * Issue: [#5527](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5527)
* Should add this column and available fields should remove it in selected fields, when select a column.
* _source should be restored automatically in selected field, if remove all the selected columns
* Should display Nested field properly in left navigation.Test nested field is broken into sub field and displayed in left nav.
    * Issue: [#5400](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5400)
* Should display Unknown type field properly in left navigation

- [ ] Function Test Suite 6: Saved Search Embeddable in Dashboard
* Saved search embeddable should be able to create and added in Dashboard. The data should be all displayed in the embeddable panel area. 
    * Issue: [#5415](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5415), [#5534](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5534)

- [ ] Function Test Suite 7: Discover Advanced Settings and related functions
* Should add missing advanced settings tests in Discover, including column modification, default column settings, and time column visibility.
    * Issue: [#5508](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5508), [#5246](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5246), [#5057](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5057), [#5538](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5538)

- [ ] Function Test Suite 8: Navigation
* Saved search should not trigger a full page reload
    * Issue: [#5066](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5066)

- [ ] Function Test Suite 9: EuiDataGrid Table 
* Discover table panel should auto-adjust its size based on time range, filter, fields and query changes
    * Issue: [#5440](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5440)
* Discover table columns can be resized

While this issue captures several key user stories and feedback, it's important to acknowledge that our understanding of user needs is ever-evolving. We welcome and encourage ongoing community engagement and will continue update this meta issue.

**Comment by LDrago27** [comment]
I want to take it.

**Comment by ananzh** [comment]
This has been partially resolved. 

@LDrago27 Could you help to add a comment there what left or could we close it?

**Comment by LDrago27** [comment]
@ananzh The following items were not able to tested.

1. Function Test Suite 2: Copy data without extra data: No easy way to test copying data to clipboard in cypress
2. Function Test Suite 5: Left Navigation Display (Should display Unknown type field properly in left navigation): Niche scenario
3. Function Test Suite 6: Saved Search Embeddable in Dashboard (When load a saved search in dashboard, sort should be loaded properly Issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5933) : Issue still open hence couldn't be tested
4. Function Test Suite 10: Saved query (From index manage page (saved object), click a saved query object created from Discover/Dashboard/Vis can load Discover with proper query and filter Issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5942) : Issue Still open hence can't be tested
5. Function Test Suite 11: Infinity Scroll in Legacy Table: Can load maximum 500 data (default size)
Scroll down should auto load 50 more data couldn't be tested since they proved to be very flaky.
