### ISSUE TITLE
[META] Data Explorer fixes

### ISSUE THREAD

**Issue by wbeckler** [opensearch-project/OpenSearch-Dashboards#5753]
The following issues address UI regressions in the Data Explorer experience that were introduced in 2.9, 2.10 or 2.11

Fixes for 2.12 (maybe should be back ported to 2.11)

- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5659
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5625
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5570
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5604
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5538
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5527
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5440
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5423
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5404
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5400
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5268
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5227
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5226
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5208

NOTE: There is a separate Data Explorer issue that covers the effort to restore the pre-2.11 version of Data Explorer:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5714

**Comment by ananzh** [comment]
Checked issues all have fixes. We are asking customers' thoughts on the fixes.

**Comment by wbeckler** [comment]
I closed the ones where fixes are merged. If the poster wants to reopen we can do that with updated details that we'll address in a subsequent release.
