### ISSUE TITLE
[Meta] Refactoring data source plugin to support add-on authentication method with plug-in module

### ISSUE THREAD

**Issue by bandinib-amzn** [opensearch-project/OpenSearch-Dashboards#5838]
This is meta tracking issue for [Refactoring data source plugin to support add-on authentication method with plug-in module](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5692).

**Tasks:**

- [X] Modify data_source and data_source_management plugin to register authentication method from plugin. 
       PR for above task: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5851/

- [X] Refactoring [client](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/data_source/server/client) and [legacy client](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/data_source/server/legacy) to use authentication registry.  
      PR for above task: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5881

- [X] Refactoring [create](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/data_source_management/public/components/create_data_source_wizard) and [edit](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/data_source_management/public/components/edit_data_source) form to use authentication registry. 
- [X] https://github.com/opensearch-project/opensearch-js/issues/696
- [ ] #6114

**Comment by bandinib-amzn** [comment]
@xinruiba Can you please help on Refactoring [create](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/data_source_management/public/components/create_data_source_wizard) and [edit](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/data_source_management/public/components/edit_data_source) form to use authentication registry? thanks!

**Comment by xinruiba** [comment]
@bandinib-amzn  Sure, happy to work on it.

**Comment by xinruiba** [comment]
@bandinib-amzn, we can also mark "Refactoring [create](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/data_source_management/public/components/create_data_source_wizard) and [edit](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/data_source_management/public/components/edit_data_source) form to use authentication registry." as complete. Thanks
