### ISSUE TITLE
[Meta] Test Orchestrator

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#6044]
RFC to the Orchestrator remote test workflow feature - https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5392

Design POC - https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5526

README doc - https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1119

### Priorities

P0

- [X] ~[Add test orchestrator script to trigger remote workflow](https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/972)~
- [X] ~[Add Github workflow for Test Orchestrator in OpenSearch Dashboards](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5720)~
- [X] ~Execute script from the release testing workflow of the functional test repo~
  - [ ] Ensure that this execution is non-blocking to the execution of integtest.sh. In a fire and forget manner, do not wait for the results.
  - [ ] For an initial deliverable we will have results showing that these tests are being executed. If it does not fire and forget then it will take in the allotted execution time (roughly 2 hours) and whatever tests we execute will add to the total test runtime.
- [ ] Clean up and add cypress configurations to [test folder](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/test) of OpenSearch Dashboards
- [ ] Onboard lightweight plugin so that they can call their tests within their repo and still be executed if infra onboard
  - [ ] Select a plugin that meets the requirements
- [ ] Update [cypress test workflow](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/.github/workflows/cypress_workflow.yml) for OpenSearch Dashboards to execute the local cypress tests
  - [ ] Will run when pull requests are made for the new code
  - [ ] Then the remote test workflow will all for the execution of tests that includes the release builds that can be downloaded and executed and provided verification
- [ ] Standardized CI groups before adding these tests. If the framework does not build with CI groups in mind then tests will be added and ran sequentially. If we add thousands of tests this will take a lot of time.
- [ ] Absorb @opensearch-dashboards-test/opensearch-dashboards-test-library into OpenSearch Dashboards
  - [ ] Potentially [@osd/test](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/packages/osd-test)
  - [ ] Everybody has to pull down OpenSearch Dashboards for their component. We can add more content and stabilize the helper functions instead of relying on an external package to help make these tests consistent and stable
- [ ] Blog
  - [ ] Talks about this work
  - [ ] Remaining work
  - [ ] Gives the ideal state and best outcome

P1

- [ ] Extend testing framework to make it easier for plugins to verify cross compatibility testing with the plugin
  - [ ] Plugins can easily reference this package as it is a part of OpenSearch Dashboards
  - [ ] Will install their plugin into the version of OpenSearch Dashboards and run a basic suite of tests for the version
  - [ ]  Additional tests can be passed from the plugin
  - [ ]  Outputs successful or failed tests
  - [ ]  Plugins can decide if they want to indicate they are fully supported or degraded
  - [x] Create 3 example plugins
    - [x] Positive (version available for engine and works)
    - [x] Negative (version not available for engine for cross compatibility)
    - [x] Partially positive (version kind of works)
  - [ ] Hook into the test orchestrator
- [ ] Work with infra to unblock onboarding the ability to listen to the remote test runners
  - [ ] Get credentials
- [ ] Campaign to add plugins to utilize workflow
- [ ] Migrate more tests from Selenium to Cypress
