### ISSUE TITLE
[Meta][UX][Multiple Datasource] Improvement to data source components in the navigation bar

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/OpenSearch-Dashboards#6216]
We introduced a few data source components to be mounted in the navigation bar 
- data source selectable: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6082
- data source multi selectable: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6211
- data source read only single selected: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6125
- data source read only aggregated view for all data sources: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6129
- data sources read only aggregated view for active data sources:  https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6129

Based on recommendations, we need to add a few improvements included below:

### Planned for 3/25 - 4/5/2024:
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6257/
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6346
- [x] #6372
- [x] #6333
- [x] #6357
- [x] #6327
- [x] #6293
- [x] #6237
- [x] #6231
- [x] #6358
- [x] #6315
- [x] #6291

### Planned for 4/8 - 4/19/2024:
- [ ] ~~[paused] change popover used by the readonly data source components to tooltip(see notes from @xeniatup for requirements)~~
- [x] change readonly data source components to show color of the button instead of greyed out or being disabled, and remove info icon https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6497
- [x] list all with active data source component should show <number of active>/<number of all> and also display unselected data sources as well https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6541
- [x] #6370
- [ ] ~~Adjust the filter component for multi select to match with requirements below~~
- [ ] ~~multi select data source component should show  <number of active>/<number of all> and change style/base component for the button group to select all or deselect all~~
- [x] #6566
- [x] #6500
- [x] #6545
- [x] #6515
- [x] #6497
- [x] #6465
- [x] #6416
- [x] #6549
- [x] #6514
- [x] #6452
- [x] #6431
- [x] #6400
- [x] #6440
- [x] #6438

### 4/22 - 4/30/2024:
- [x] #6594
- [x] #6570
- [x] #6597
- [x] #6617

**Comment by xeniatup** [comment]
Adding a more detailed view for: **Change popover used by the readonly data source components to tooltip**

The UX recommendation is to show a popover (triggered by click) when user can select a single data source/multi-select data sources:

![single-select-click](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105245012/d4dc10c2-4466-4ed5-9273-933c5e076fae)

<img width="575" alt="Screenshot 2024-03-27 at 5 29 22 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105245012/5fcae933-955c-48f8-b9f7-314bd0385aaa">


And for providing context (all read only: data source read only single selected, data source read only aggregated) the recommendation is to trigger a tooltip on mouse over.

![read-only-hover](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105245012/8437a89d-5534-45a0-8514-74c21057e9ce)

<img width="888" alt="Screenshot 2024-03-27 at 5 29 11 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105245012/c7052f87-9a93-4737-962f-9e293f7d1cf8">
