### ISSUE TITLE
[Discover] Bug Tracking Meta Issue

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#6292]
## Regression Bug
- [ ] [[BUG] UI Glitch when mouseover Discover document](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5230)
- [ ] [[BUG] [Discover] Inner scrollbar on datagrid](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5231)
- [ ] [[BUG] ScopedHistory instance has fell out of scope for basePath: /app/data-explorer](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5476)
- [ ] [[BUG][Data Explorer] Table rendering flakiness](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5495)
- [ ] [[BUG] Log table rows in the "New Discover" UI flicker after scrolling to the bottom](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5512)
- [ ] [[BUG] Discover 2.0 - Auto re-sizing of columns happens inappropriately (and frequently) when using saved queries](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5524)
- [ ] [[BUG] Unable to use shared links when Store URLs in session storage is enabled](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5588)
- [ ] [[BUG] column scaling regression in discover](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5671)
- [ ] [[BUG] Copy Link button in Share does not actually copy the link on Safari](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5629)
- [ ] [[BUG] Saved Search horizontal resizing not working](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5653)
- [ ] [[Discover] Narrow document details column](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5683)
- [ ] [[BUG] Can't view surrounding documents when there's a "+" in the id](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5711)
- [ ] [[BUG] Fix glitch for save query management](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5833)
- [ ] [[BUG][Discover] Resizable flyout and document details](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5903)
- [ ] [[BUG] Discover crashed when loading a saved search from saved object list in dashboards management](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5942)
- [ ] [[BUG] Context page in discover does not highlight the document row for which we see the surrounding docs](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6048)

## Other Bug
- [ ] [[BUG] List of Available fields on Discover page is not correctly refreshed](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1256) 
- [ ] [[BUG] label template not showing value for url-image](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1888) 
- [ ] [[BUG] Field list does not reflect all the available fields for the selected index](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4439)
- [ ] [[BUG][Discover] Unable to sort boolean scripted fields](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5126)
- [ ] [[BUG][Discover] Unable to sort Date scripted fields](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5127)

**Comment by ananzh** [comment]
## 2.14 Plan
- [ ] [[BUG] UI Glitch when mouseover Discover document](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5230)
 - Owner:
 - L:
- [ ] [[BUG] [Discover] Inner scrollbar on datagrid](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5231)
 - Owner:
 - L:
- [ ] [[BUG] ScopedHistory instance has fell out of scope for basePath: /app/data-explorer](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5476)
 - Owner:
 - L:
- [ ] [[BUG][Data Explorer] Table rendering flakiness](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5495)
 - Owner:
 - L:
- [ ] [[BUG] Log table rows in the "New Discover" UI flicker after scrolling to the bottom](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5512)
 - Owner:
 - L:
- [ ] [[BUG] Discover 2.0 - Auto re-sizing of columns happens inappropriately (and frequently) when using saved queries](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5524)
 - Owner:
 - L:
- [ ] [[BUG] column scaling regression in discover](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5671)
 - Owner:
 - L:
- [ ] [[BUG] Saved Search horizontal resizing not working](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5653)
 - Owner:
 - L:
- [ ] [[BUG] Can't view surrounding documents when there's a "+" in the id](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5711)
 - Owner:
 - L:
- [ ] [[BUG] Fix glitch for save query management](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5833)
 - Owner:
 - L:
- [ ] [[BUG] Discover crashed when loading a saved search from saved object list in dashboards management](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5942)
 - Owner:
 - L:

**Comment by sandervandegeijn** [comment]
There are also quite some bugs in the Dashboards app, but in the Dashboards plugins of other components (like security, alerting). Are these tracked here as well?

**Comment by ashwin-pc** [comment]
@sandervandegeijn OpenSearch Dashboard bugs are tracked under the issues tab: https://github.com/opensearch-project/OpenSearch-Dashboards/issues

Other Plugin specific issues are tracked in their own repo. Is there something specific you are looking for?

**Comment by sandervandegeijn** [comment]
I have filed some under the plugins, i.e:

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6490
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/946
https://github.com/opensearch-project/security-dashboards-plugin/issues/1891
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6338
https://github.com/opensearch-project/alerting-dashboards-plugin/issues/886
https://github.com/opensearch-project/dashboards-maps/issues/573
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/964
https://github.com/opensearch-project/alerting/issues/1354
https://github.com/opensearch-project/alerting-dashboards-plugin/issues/760

But my issues are no more important than others. If you look through the plugin repos there are some that aren't that actively managed. Untriaged bugs, release issues for opensearch versions in the past, etc. But these plugins are shipped with opensearch by default and bugs in them will impact the Dashboards usability.

**Comment by ananzh** [comment]
2.16 bug plan
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6991
