### ISSUE TITLE
[VisBuilder] 2.15 GA meta tracking issue

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#6419]
## Clean out experimental
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6436

## Bug fixes
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5643
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5644
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5645
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5646
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6680
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6679

**Comment by AdaptiveStep** [comment]
Too bad that the vizbuilder doesn't work that well.
It's much more pleasant and intuitive than working with old-school buckets.

**Comment by ashwin-pc** [comment]
@AdaptiveStep can you add what doesn't work that well in this issue here? I'd love to hear your thoughts on whats missing and what we can do to improve and close those gaps

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2280

**Comment by ananzh** [comment]
@AdaptiveStep can you help us open an issue for more detailed feedback? This one is more like a tracking issue for release. 
We would love to hear your thoughts. Thanks in advance.

**Comment by ananzh** [comment]
Resolve this as all issues are resolved.
