### ISSUE TITLE
VisBuilder Release: Moving Beyond Experimental Phase Meta Issue

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#6773]
- [x] VisBuilder Scroll bug: I can scroll to the right on drag and then the pane gets cut off and no easy way to get back without dragging a field in the opposite direction
- [x] Visbuilder Toggle bug: after clicking on Toggle legend affordance, legend went away, but can’t toggle to get back (changing Chart doesn’t help). If I start with it off, it won’t go away on toggle?
- [ ] Visbuilder index popup bug: Adding timestamp to x-axis causes this error to appear. 
- [ ] Getting started experience: As a user, I want to be able to get to VisBuilder as quickly and seamlessly as possible based on the workflow that I am trying to achieve. As a user, I can easily decide on a path, e.g. start with a known vis type, build with vega, or or build with ui.

**Comment by LDrago27** [comment]
@ananzh Sure I can pick up the task.

**Comment by ananzh** [comment]
close this one due to duplication of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6419
