### ISSUE TITLE
[Meta][2.16] Support Version Decoupling in OpenSearch Dashboards Plugins

### ISSUE THREAD

**Issue by ZilongX** [opensearch-project/OpenSearch-Dashboards#6849]
### Context

OpenSearch plugins currently tightly couple their versions with the underlying OpenSearch/OpenSearch Dashboards version. This tight coupling can lead to challenges in maintaining and upgrading plugins independently. This meta issues tracks the decouple efforts of the plugin versions from the OpenSearch versions, allowing for more flexibility in managing and updating plugins.

More details is available at `RFC Plugins Version Decoupling` - https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5877

**Here is the detailed tracker of PR/Issues for supporting version decoupling in OpenSearch Dashboards Plugins**

- [x] https://github.com/opensearch-project/dashboards-query-workbench/issues/332
- [x] https://github.com/opensearch-project/dashboards-search-relevance/issues/396 
- [x] https://github.com/opensearch-project/security-dashboards-plugin/issues/1971
- [x] https://github.com/opensearch-project/dashboards-notifications/issues/206
- [x] https://github.com/opensearch-project/ml-commons-dashboards/issues/328 
- [x] https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/764 
- [x] https://github.com/opensearch-project/index-management-dashboards-plugin/issues/1063 
- [x] https://github.com/opensearch-project/dashboards-maps/issues/620

**Comment by kavilla** [comment]
cc: @AMoo-Miki
