### ISSUE TITLE
[Discover-Next] Meta Issue for Bugs, Updates, Fast-Follows

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#6957]
#### Issues list

- [ ] #7032
- [x] #7036
- [ ] #7037
- [x] #7038
- [ ] #7039
- [x] #7040
- [ ] #7041
- [x] #7042
- [x] #7046
- [ ] Add more tests
- [ ] `stats` display in table
   - [ ] is this log patterns?

#### Query Assist
- [ ] Clean up reference of `queryEditorHeaderRef` [[COMMENT](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7034/files#r1641529201)][[COMMENT](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7034/files#r1641567709)]
- [ ]  Pass dataSource to TopNavMenu once dataSource work is completed [[COMMENT](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7034/files#r1641532625)]

#### Async queries (not in review into main yet)
- [ ] Loading state, ensuring the loading is giving a proper indication for long standing queries

#### Pending items post second bug bash

- [ ] #7043
- [ ] Async queries, when navigating the request, the request is still polling
  - [ ]  Should we cancel or should we let it go and not fire again on landing 
- [ ] Better error handling
- [ ] Extend OSD field type mapper function registration points
- [ ] Remove temp logic for https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7106 if not needed
- [ ] Highlight fields if PPL where filter
- [ ] Time field width gets rendered before data populates causing time column to get cropped and displayed poorly
   - [ ] Validate this is still happening after all bug fixs
   - [ ] If it is still happening ensure we don't render until we got the data
- [ ] UI shifts when hovering over quick filter buttons
   - [ ] Validate this is still happening after all bug fixs
   - [ ] This could be fixed with the timefield render issue
   - [ ] If not this could be setting a min width in the sidebar to prevent pushing from canvas
- [ ] when toggling on and then off, we force the query to be `''` and language to `kuery` for DQL
   - [SOURCE](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/data/public/ui/settings/settings.ts#L52)
   - This one done to make sure users get back to a default state if the previous query was not natively supported like PPL or SQL.
   - We should get UX involved to ensure that's ok or at least maybe we can pull from the Advanced Setting `search:queryLanguage`
- [ ] clean up styling
   - [ ] clean up styles location of query editor and query bar [[COMMENT](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7001#discussion_r1636810164)]
     - for 2.15 to reduce the number of changes (and potential impact) added the styles for the editor in the same location as the query bar. We should clean this up to follow standards.
   - [ ] better naming related to function [[COMMENT](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7001#discussion_r1636812450)] 
   - [ ] We dont support IE, clean up wording to be more accurate [[COMMENT](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7001#discussion_r1637167243)]
   - [ ] Verify if we support Edge still [[COMMENT](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7001#discussion_r1637167243)]
   - [ ] Create issue for stylelint for classNames [[COMMENT](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7001#discussion_r1637339390)]
- [ ] move redundant components from the query bar and query editor to the a shared location [[EXAMPLE](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/8a59bfe20a33101661c4aeaafdf88f321bd23813/src/plugins/data/public/ui/query_editor/no_data_popover.tsx)]
- [ ] code clean up within query editor and query bar
  - [ ] if more params added to settings in UI service then use object [[COMMENT](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7001#discussion_r1638745574)]
  - [ ] avoid single statement if block with no braces [[COMMENT](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7001#discussion_r1637012388)]
  - [ ] use `item || undefined` instead of a ternary operator that checks the item first [[COMMENT](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7001#discussion_r1637021714)]
  - [ ] do we need query editor rect anymore once we add suggestions? if so should we keep it undefined?[[COMMENT](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7001#discussion_r1637006688)]
  - [ ] make issue with `TODO` for entire repo, follow up with specific issues within the query editor [[COMMENT](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7001#discussion_r1636813464)] 
- [ ] re-add fetching index patterns for suggestions [[COMMENT](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7001#discussion_r1637013510)]
   - [ ] clean up ported over fetch index patterns file [[COMMENT](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7001#discussion_r1637343477)]
   - [ ] better fallback for lazy components [[COMMENT](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7001#discussion_r1638879093)]
- [ ] follow up on `TODO: MQL` inline comments and convert to issue [[COMMENT](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6957)]
- [ ] improve readability [[COMMENT](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7001#discussion_r1636991625)]

<details>
<summary> Archived: 2.15 experimental release (post first bug bash)</summary>

## Blockers for 2.15 experimental release

If to target in 2.15 experiment the following list is required and fixing major bugs discovered during a bug bash. Here's what we will need (NOTE: subject to change).
 
Our current criteria is default state (disabled by config value and/or toggled off in advanced settings) is completely intact within Discover, with Data Explorer, with in Observability, with in dashboards and visualizations with OpenSearch having Flint & ML, only Flint, or only ML.

If the config is enabled and toggled on in advanced settings any major issues below should be fixed:

### feature flag: @kavilla
- [ ] get state machine of different experiences for testing purposes
- [ ] PR to get the enhancements out of repo
- [x] Advanced Setting toggle completely reverts back to the query bar (old language selector with option for dql, lucene) not just the input
  - [x] enabled should be exactly the old way
  - [x] verify no lingering issues from when it was on
- [x] restore the redirect for default way [[link](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/data_explorer/public/components/sidebar/index.tsx#L62)]
- [x] don't show new query bar outside discover

### datasource: @paulstn
- [ ] datasource type indicating if flint or not (ideally it should be more generic like), or maybe we just utilize something like type on the data source like (polling or not default)
  - [ ] this is blocker for @joshuali925 if the domain supports query assist or not 
     - the implication here is that we want in context query assistant suggestion related to the datasource, so we need to check if the data source has ml commons or not.
       - we could check if an existing API is on the data source when switching the source
       - consider fast follows and base query assist on your default (local cluster)
       - make it an advanced setting (that we can override when hosting) that lets people enable query assist or not
  - [ ] this could be a blocker for sean's work as he will need to key off this value to do async or not
      - an option could be to just allow any language for any data source and we just show the appropriate error messages
- [ ] this can be moved to fast follows based on previous point about appropriate error messages, but data sources should poplate the language switcher with languages available for that data source. it should probably be related to the data source and data source connection work but it could be added here: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/feature/discover-next/src/plugins/data/public/ui/types.ts#L45 as `unsupportedDataSourceConnections` i'm fine with the initial implmenetation using the hardcode data source types but something we need to track when we remove those hard coded values for registration points

### sql (async): @sean li
- [ ] loading spinner when querying
  - [ ] need to verify if it's ok just to showing loading for now and fast follow as different loading status's like "loading", "not-loading", "processing" 
- [ ] SQL (async) shouldn't be an option, use datasource information to pass to SQL search strategy to do async work or not
- [ ] Don't create temporary index pattern for dataframe if the data source is a specific index, [[HERE IS THE CODE IT'S HAPPENING]](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/data/public/search/search_service.ts#L150) will solve this issue:
  <img width="267" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/12060704/c25c97f3-4aa8-4f67-b840-c8994a073a97">
- [ ] ensure search service public and server folder are aligned in  implementation since we only modified public folder, related to the dataframeScache and stuff

Archived: Query Assist: @joshuali925 (Use comment below)
### query assist: @joshuali925
- [ ] verification and validation next steps with query assist AND flint enabled to avoid issues in that state
- [ ] any bugs within this workflow or endpoint
- [ ] based on paul's work, another suggestion could be another toggle in advanced settings to let the admin decide if to disable or enable in general as a workaround until GA
- [ ] user preference for toggling time filter?

### sql (async): @sean li:
- [ ] clean up dataframe and dataframes cache, we likely are doing redudant work. consolidate
- [ ] ppl (async) support

### feature flag: @kavilla 
- [ ] query enhancements plugin and repo
</details>

**Comment by sejli** [comment]
### Async query timeouts
In the case that a polling job gets stuck/starts to hang for too long, there should be a mechanism in place to abort it. Advanced settings can have some configurable timeout that will stop the ongoing query. To do that, two things need to happen:
1. The polling itself must stop. Upon timeout, the polling logic should return true and quit.
2. `DELETE /_plugins/_async_query/{queryId}` should be run to cancel the job in the backend if it's still ongoing.

**Comment by joshuali925** [comment]
query assist: 
- [ ] verification and validation next steps with query assist AND flint enabled to avoid issues in that state
   - opened PR [#6972](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6972/commits/62f6169488aa02b42ab177162ef21ab2a4dd5759)
- [ ] any bugs within this workflow or endpoint
   - needs more testing
- [x] based on paul's work, another suggestion could be another toggle in advanced settings to let the admin decide if to disable or enable in general as a workaround until GA
   - this is not needed since item 1 is doable
- [x] user preference for toggling time filter?
   - this is not needed per UX, because current discover already mentions about expanding time range if query didn't match results. it's a generic UX problem
