### ISSUE TITLE
[Meta][2.16] Discover Bug Fix / Enhancement Tracking Issue

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#6991]
### Bug Fix  

- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6982 (Owner: @ananzh Status: in progress)
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6838 (Owner: @ananzh Status: in progress)
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5942 (Owner: @ananzh Status: in progress)
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5524 (Owner: @ananzh Status: in progress)
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5833
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6457

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6292
