### ISSUE TITLE
[Meta][2.16] VisBuilder Integration and Bug Fix tracking issue

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#6992]
## Enhancement

- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7015
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7083
  - [x] [2.16]https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7067

## Bug

**Comment by LDrago27** [comment]
@ananzh I could help you out with some of the related bugs.

**Comment by ananzh** [comment]
Resolved
