### ISSUE TITLE
[META] New version of navigation

### ISSUE THREAD

**Issue by SuZhou-Joe** [opensearch-project/OpenSearch-Dashboards#7027]
New version of left navigation can help users better focus on the `use case` or features.

## 2.16
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7029
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7061
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7073
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7094
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7118
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7131
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7132
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7147
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7148
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7283

## 2.16 -- tracker for plugins
- [ ] https://github.com/opensearch-project/dashboards-observability/pull/1926
- [ ] https://github.com/opensearch-project/dashboards-reporting/pull/369
- [ ] https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1085
- [ ] https://github.com/opensearch-project/security-dashboards-plugin/pull/2022
- [ ] https://github.com/opensearch-project/ml-commons-dashboards/pull/337
- [ ] https://github.com/opensearch-project/dashboards-maps/pull/635
- [ ] https://github.com/opensearch-project/dashboards-search-relevance/pull/406
