### ISSUE TITLE
[Meta][VisBuilder]

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#7083]
## Background 
While VisBuilder reached GA in version 2.15, it is currently limited to a few chart types and lacks the comprehensive set of controls necessary for complex visualizations. Meanwhile, the existing visualization library, vislib, cannot fulfill these requirements. For instance, new features like support for multiple query languages (PPL, SQL) and the ability to handle multiple data sources demand a more robust and flexible visualization tool. Additionally, adding controls to different visualization types using the current setup involves excessive effort. Maintaining multiple libraries such as vislib, timeline, and vega is inefficient and unsustainable.

### User Perspective Requirement
* Enriched controls for current visualizations in VisBuilder
* More chart types in VisBuilder
* Migrate existing saved visualization to VisBuilder

### Developer Perspective Requirement
* Simplify the customization process for developers, minimizing efforts and consolidating the use of a single visualization library.

To address these challenges, we propose to enhancing the current VisBuilder to leverage these requests to offer users powerful tools for data analysis and reporting, thereby improving the overall user experience and functionality of OpenSearch Dashboards. 

## Detailed Deliveries and Tasks:

- [ ] Transition from vislib to a single, unified visualization library that can support the required features: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7067
- [ ] Develop and integrate enriched control options for line charts.
- [ ] Develop and integrate enriched control options for bar charts.
- [ ] More chart types in VisBuilder: Pie
- [ ] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7082
