### ISSUE TITLE
[Meta] Discover 2.0

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#7250]
This is a meta issue for all Discover 2.0 related features:

## Features

- [ ] PPL and SQL in Discover
- [ ] Query Assist in Discover
- [ ] Async Query support in Discover
- [ ] New language specific query bar's in Discover
- [ ] DQL, SQL and PPL Autocomplete in Discover
