### ISSUE TITLE
Release version 1.2

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch-Dashboards#833]
Coming from [opensearch-build#567](https://github.com/opensearch-project/opensearch-build/issues/567), release version 1.2. Please follow the following checklist.

### Preparation

- [x] Assign this issue to a release owner. (@seanneumann)
- [x] Finalize scope and feature set and update [the Public Roadmap](https://github.com/orgs/opensearch-project/projects/1).
- [x] Create, update, triage and label all features and issues targeted for this release with [`v1.2.0`](https://github.com/opensearch-project/OpenSearch-Dashboards/issues?q=label%3Av1.2.0+).

### CI/CD

- [x] Increment version on main to `1.2.0`. https://github.com/opensearch-project/OpenSearch-Dashboards/pull/802
- [x] ~~Ensure working and passing CI.~~ N/A for 1.2. ETA 1.3

### Pre-Release - Nov 2

- [x] Branch and build from a `1.2` branch.
- [x] Update your branch in the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.2.0/opensearch-dashboards-1.2.0.yml). (https://github.com/opensearch-project/opensearch-build/pull/869)
- [x] Feature complete, pencils down.

### Release Testing - Nov 10

- [x] Manually running BWC testing script @ananzh 
- [x] Final Sanity testing of Core Dashboards
- [x] Fix any show stopping issues found in testing

### Release - Nov 18

- [ ] ~~Complete [documentation] [Custom Branding](https://github.com/opensearch-project/documentation-website/issues/241)~~ 
- [x] Gather, review and publish release notes. @seanneumann [#944]
- [x] Verify all issues labeled for this release are closed or labelled for the next release.

### Post Release

- [x] Create [a release tag](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#tagging).
- [x] Suggest improvements to [this template](https://github.com/opensearch-project/opensearch-plugins/templates/release.md).
- [x] Conduct a postmortem, and publish its results. https://github.com/opensearch-project/opensearch-build/issues/880

**Comment by peternied** [comment]
@seanneumann Still on target for the manual BWC to complete tomorrow?

**Comment by seanneumann** [comment]
> @seanneumann Still on target for the manual BWC to complete tomorrow?

Hi @peternied - we're updating the issue to reflect the actual dates. The manual testing for BWC will come later.

**Comment by peternied** [comment]
@seanneumann Until Friday the 12th at noon PST, any tests that use distribution downloader were running against old bits and need to be rerun.  Can you please see if your team was impacted, rerun the tests, and then mark the tests run as completed in https://github.com/opensearch-project/opensearch-build/issues/954?

**Comment by tmarkley** [comment]
All steps are complete. Postmortem details will be published in https://github.com/opensearch-project/opensearch-build/issues/880.
