### ISSUE TITLE
[NodeJS] Dashboards is not compatible with nodejs client 

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#837]
### Tasks
* [x] hookup @opensearch-project/opensearch to dashboards
  PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1181
* [x] fix issues in scr/core/sever/saved_objects 
  Issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1216
  PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1223
* [x] fix issues in src/core/server/core_usage_data
  Issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1224
  PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1225
* [x] fix issues in src/core/server/opensearch
  Issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1193
  PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1194
* [x] `yarn osd bootstrap` works 
* [x] Unit tests all pass
   PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1255
* [x] Integration tests all pass 
   Issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1245
* [x] Functional tests all pass
   Issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1246

**Describe the bug**

We forked nodejs client (repo [here](https://github.com/opensearch-project/OpenSearch-js)) from v7.14 and delete all the non-oss api between v7.10 to v7.14.  nodejs client v7.14 is not compatible with current Dashboards due to type change.

For example, below is the indices.get defined in nodejs v7.14:
```
get<TContext = unknown>(params: T.IndicesGetRequest, options?: TransportRequestOptions): TransportRequestPromise<ApiResponse<T.IndicesGetResponse, TContext>>
```
which is different from its definition in nodejs v7.10:
```
get<TResponse = Record<string, any>, TContext = Context>(params?: RequestParams.IndicesGet, options?: TransportRequestOptions): TransportRequestPromise<ApiResponse<TResponse, TContext>>
```

If we refers to @opensearch-project/opensearch and change all the client from KibanaClient to OpenSearchDashboardsClient, we could see type undefined errors from bootstrap. Below is one example:

```
ERROR [bootstrap] failed:
ERROR Error: Command failed with exit code 1: /usr/share/yarn/bin/yarn.js run osd:bootstrap
      error Command failed with exit code 1.
      $ node scripts/build_ts_refs && node scripts/register_git_hook
      ERROR Error: Command failed with exit code 1: /home/anan/work/OpenSearch-Dashboards/node_modules/typescript/bin/tsc -b tsconfig.refs.json --pretty
            src/core/server/saved_objects/migrations/core/opensearch_index.ts:71:33 - error TS2345: Argument of type '{ exists: true; indexName: string; aliases?: Record<string, IndicesAlias> | undefined; mappings?: MappingTypeMapping | undefined; settings: IndicesIndexSettings | IndicesIndexStatePrefixedSettings; }' is not assignable to parameter of type 'FullIndexInfo'.
              Types of property 'aliases' are incompatible.
                Type 'Record<string, IndicesAlias> | undefined' is not assignable to type '{ [name: string]: object; }'.
                  Type 'undefined' is not assignable to type '{ [name: string]: object; }'.

            71   return assertIsSupportedIndex({ ...indexInfo, exists: true, indexName });
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**To Reproduce**
1)`yarn add @opensearch-project/opensearch`
2) search @elastic/elasticsearch in non package.json files and replace it with @opensearch-project/opensearch
3) go to `src/core/server/saved_objects/migrations/core/opensearch_index.ts` change KibanaClient to OpenSearchDashboardsClient

# Impact to Plugins

The major change brought by new opensearch-js client is that the api types are looser ( [here](https://github.com/opensearch-project/opensearch-js/blob/main/api/new.d.ts)  ) than the original ( [here](https://github.com/opensearch-project/opensearch-js/blob/main/index.d.ts) ) . For example, comparing how bulk api is previously defined as 

```
bulk<TResponse = Record<string, any>, TRequestBody extends RequestNDBody = Record<string, any>[], TContext = Context>(params?: RequestParams.Bulk<TRequestBody>, options?: TransportRequestOptions): TransportRequestPromise<ApiResponse<TResponse, TContext>> 
```

While in the new.d.ts,  the bulk api is now changed to:

```
bulk<TSource = unknown, TContext = unknown>(params: T.BulkRequest<TSource>, options?: TransportRequestOptions): TransportRequestPromise<ApiResponse<T.BulkResponse, TContext>>
```
Since it is a looser typed client, we don’t see much breaking changes in the dashboards code base. Most changes are related to type fixes which should not affect plugin owners. For most plugins, they use client interact with data plugin. For index management plugin, it uses Client defined in /src/core/server/opensearch/legacy. Though this client is imported from 'elasticsearch' but this is actually "@types/elasticsearch": "^5.0.33" from [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/elasticsearch). Currently, we don’t plan to change the legacy server and client. 

To sum up, we don’t see breaking changes for plugins. I listed some steps to try using anomaly-detection below. SInce we are still fixing the PRs, could try with my [test branch](https://github.com/ananzh/OpenSearch-Dashboards/tree/feature/fix). **However, since none of the plugins are using opensearch/opensearch-dashboards 2.0 or bump the node&package version accordingly, it is hard to evaluate the full impact. I would highly suggest that plugins bump to version 2.0 with node v14 and upgraded packages. Use the below steps to hook up with the opensearch-dashboards. Run all the unit tests, integration tests, and sanity tested the plugin.** 

**Anomaly Detection build & run steps**

1. Use OpenSearch main branch (v2.0). Fork and Clone [anomaly-detection backend plugin](https://github.com/opensearch-project/anomaly-detection) (https://github.com/opensearch-project/anomaly-detection)
2. run `./gradlew build` in anomaly-detection directory
3. run `./gradlew :run` to run a single node cluster with anomaly-detection plugin
4. Fork and clone [anomaly-detection-dashboards-plugin](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin) (https://github.com/opensearch-project/anomaly-detection-dashboards-plugin) into the `<rootDir>/plugins` for OpenSearch Dashboards with the nodejs client hooked up
5. make sure to use node 14.18.2 and run `yarn osd bootstrap` inside of OpenSearch Dashboards `<rootDir>`
6. update "opensearchDashboardsVersion" in  `<rootDir>/plugins/anomaly-detection-dashboards-plugin/opensearch_dashboards.json` from "1.3.0" to "2.0.0"
7. update `<rootDir>/config/opensearch_dashboards.yml` and add "openserch.ignoreVersionMismatch: true"  in this config file. This is because plugin is still using v1.3.0 while dashboards is v2.0.0. This line will [ignore the version mismatch check](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/895142902cfc94160ea66b556ddcb165b8b1c5c2/src/core/server/opensearch/version_check/ensure_opensearch_version.ts#L167) (https://github.com/opensearch-project/OpenSearch-Dashboards/blob/895142902cfc94160ea66b556ddcb165b8b1c5c2/src/core/server/opensearch/version_check/ensure_opensearch_version.ts#L167).
8. run `yarn start` inside of OpenSearch Dashboards <rootDir> and verify anomaly-detection plugin is running up
9. run tests and play with anomaly-detection plugin 

Running anomaly-detection:
<img width="1612" alt="Screen Shot 2022-03-02 at 11 31 37 PM" src="https://user-images.githubusercontent.com/79961084/156639760-7bfcf0c1-99a2-4442-bc29-3a466d4c3b09.png">

Unit test results:
<img width="386" alt="Screen Shot 2022-03-02 at 11 33 48 PM" src="https://user-images.githubusercontent.com/79961084/156639793-2af6c79c-2d68-4bc4-a473-91a8603fa4a7.png">

Integration test results:
<img width="1667" alt="Screen Shot 2022-03-02 at 11 59 37 PM" src="https://user-images.githubusercontent.com/79961084/156639833-cbef3706-423a-4b88-98b9-c9ac2c777226.png">

<img width="1668" alt="Screen Shot 2022-03-03 at 12 01 55 AM" src="https://user-images.githubusercontent.com/79961084/156639974-fca230b0-0d6d-4999-9e48-a1aa90a3a24d.png">

<img width="1670" alt="Screen Shot 2022-03-03 at 12 07 16 AM" src="https://user-images.githubusercontent.com/79961084/156639993-4efbd9a7-d5c1-43f8-90bf-6ab1ac85bd87.png">

**Expected behavior**
Update Dashboards in 2.0 with type changes

**OpenSearch Version**
2.0

**Dashboards Version**
2.0

**Plugins**
plugins also need to update the types
