### ISSUE TITLE
[Release] 1.2 Release Retrospective

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/OpenSearch-Dashboards#984]
### Went Well

* Organizing the release in GitHub was a nice way to keep track of where we were at in the process and what to expect. This also allowed us to align with other repos very easily.
* @seanneumann was able to get more involved with GitHub as the release owner. Thanks @ananzh and @kavilla for the help!
* @kavilla did a great job managing scrum.
* The Dashboards team had their work done on time.
* The team was able to focus on fundamentals and foundational work such as CI/CD and the Node.js upgrade.

### Areas to improve

* Documentation wasn't completed for the custom branding feature.
* There were last-minute plugin changes.
* The state of testing is not clear. It would be great to have an automated daily mechanism to report on tests.
* Dates for release milestones in the issue weren't initially clear.
* ZenHub access/permissions is still not where we want it.
* Need to focus on UX facing innovations and features once fundamentals are complete.
* Last-minute maps change https://github.com/opensearch-project/OpenSearch-Dashboards/pull/893

### Action Items

- [x] (@kavilla) Custom branding documentation: https://github.com/opensearch-project/documentation-website/issues/241
- [ ] (@ahopp) Custom branding blog post: https://github.com/opensearch-project/project-website/issues/441
  * Overall, we need to ensure that documentation and blog posts are actually complete before the release.
- [x] (@seanneumann) Coordinate check-ins with Visualizations team.
- [x] (@seanneumann) Determine what metrics we want to gather for automated testing. https://github.com/opensearch-project/opensearch-dashboards/issues/1035
- [x] (@tmarkley) Continuous improvement with ZenHub, include topics in the end of sprint retrospective.
- [x] (Release owner) Ensure that related work (Visualizations, Maps, etc.) is tagged in our repo with the release.
- [x] Plugins need to bump their version sooner than the week before the release. (this is being discussed in the broader project retrospective.

**Comment by tmarkley** [comment]
Should we keep this open for our 1.2 retrospective items?

**Comment by kavilla** [comment]
@tmarkley could we close this issue?

**Comment by tmarkley** [comment]
@ahopp are we no longer doing a custom branding blog post?

**Comment by dblock** [comment]
1.2 has shipped a long time ago, closing
